sonar.projectKey=multi-cloud-devops-platform
sonar.projectName=multi-cloud-devops-platform
sonar.sources=.
sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**,**/.git/**,**/terraform/.terraform/**,**/terraform/terraform.tfstate*
