name: Multi-Cloud CD

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:

  deploy-aws:
    name: Deploy AWS Infrastructure
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.8

      - name: Terraform Init
        working-directory: terraform/aws
        run: terraform init

      - name: Terraform Plan
        working-directory: terraform/aws
        run: terraform plan

      - name: Terraform Apply
        working-directory: terraform/aws
        run: terraform apply -auto-approve


  deploy-azure:
    name: Deploy Azure Infrastructure
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: |
            {
              "clientId": "${{ secrets.AZURE_CLIENT_ID }}",
              "clientSecret": "${{ secrets.AZURE_CLIENT_SECRET }}",
              "subscriptionId": "${{ secrets.AZURE_SUBSCRIPTION_ID }}",
              "tenantId": "${{ secrets.AZURE_TENANT_ID }}"
            }

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.8

      - name: Terraform Init
        working-directory: terraform/azure
        run: terraform init

      - name: Terraform Plan
        working-directory: terraform/azure
        run: terraform plan

      - name: Terraform Apply
        working-directory: terraform/azure
        run: terraform apply -auto-approve