replicaCount: 2

image:
  repository: bavajan12/frontend
  tag: "latest"
  pullPolicy: IfNotPresent

imagePullSecrets: []

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext:
  fsGroup: 1000

securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL

containerPort: 3000

service:
  type: ClusterIP
  port: 3000
  targetPort: 3000

config:
  APP_ENV: production

resources:
  requests:
    cpu: 100m
    memory: 64Mi
  limits:
    cpu: 300m
    memory: 256Mi

livenessProbe:
  enabled: true
  path: /
  initialDelaySeconds: 20
  periodSeconds: 10

readinessProbe:
  enabled: true
  path: /
  initialDelaySeconds: 10
  periodSeconds: 5

ingress:
  enabled: false
  className: nginx
  annotations: {}
  hosts:
    - host: multi-cloud-devops.example.com
      paths:
        - path: /
          pathType: Prefix
  tls: []

nodeSelector: {}

tolerations: []

affinity: {}